### ISSUE TITLE
Support `:optimizations :none`

### ISSUE THREAD

**Issue by crisptrutski** [bensu/doo#11]
Given the benefits both for compilation and evaluation times in a tight feedback loop, it would be great to support this compilation mode simply out of the box.

Solutions have been offered at https://github.com/mike-thompson-day8/cljsbuild-none-test-seed

**Comment by bensu** [comment]
This is definitely on the roadmap but not trivial to do. With this reference it will be much easier, thanks!

**Comment by crisptrutski** [comment]
No problem - here's [more discussion](https://github.com/cemerick/clojurescript.test/issues/75#issuecomment-121367967) if you're interested

**Comment by moea** [comment]
I looked into this a little - that crazy Javascript is for the case where the build has no `:main`.  At least with 3308 (which I think you're requiring), if a build targets `:nodejs`, has a valid `:main`, and a relative `:output-dir`, the generated module works fine with the `eval` based node runner you currently have.

i.e.

```clojure
{:source-paths ["src" "test"]
 :compiler {:output-to "target/testable.js"
            :output-dir "target"
            :main 'example.runner
            :optimizations :none
            :target :nodejs}}
```

This seems more than good enough, given that `:main` is part of how you intend your library to be used.  It seems like the `:none` restriction could be dropped from the project, unless I've missed something.  Thoughts?

**Comment by bensu** [comment]
Thanks!

I've already started working on this. I also thought that the node runner would work, but then when I tried it, it failed. Can you supply a small example where `lein doo node test` or `(run-script ... ...)` works for `:optimizations :none`?

If that is the case, I'll drop the `:none` requirement for node. The rest of the runners are still an open issue though.

**Comment by moea** [comment]
`lein doo node test` works for me in this slightly-modified version of your example project: https://github.com/bensu/doo/compare/master...nervous-systems:none-example

**Comment by bensu** [comment]
Great, thanks! I could reproduce this. I'll lift the restrictions for node soon, I'll first keep trying with the rest of the runners, and if I don't get very far I'll make `(and node? none?)` the exception.

**Comment by bensu** [comment]
`:optimizations :none` for node was added in `0.1.4-SNAPSHOT` (deployed). Hopefully I'll incrementally add `:none` support for the other runners in this SNAPSHOT release.

**Comment by bensu** [comment]
I pushed another `0.1.4-SNAPSHOT` that adds `:none` support for both `slimer` and `phantom`. @moea @crisptrutski would you mind trying it? There are many changes, and some things may break.

**Comment by crisptrutski** [comment]
While I can run your examples using the lein plugin, no joy yet hooking this up with boot. 

One thing I've noticed is that the generated `testable.js` contains relative paths, but even manually updating this file, or executing the runner script from the generated file directory does seem to work correctly - the `ClojureScript could not load :main, did you forget to specify :asset-path?` error is kicking in.

Perhaps I was missing something obviously, was pretty sleepy by the time I got to this.

**Comment by crisptrutski** [comment]
@bensu had a chance to look at this again, and found the issue.

Essentially when using `boot` you need to use relative paths, because the file paths are not fixed (they're temp directories during tasks but then are written to `:target-path`). This means that the `testable.js` style file can't practically use absolute paths.

This would not be an issue, except that the base URL for `pagePath` is the resource file for the script, rather than the generated JS error. 

IMHO the best solution is just to change the `pagePath` - something as simple as `var pagePath = fs.absolute("doo.html");` should be fine, or you could use that final argument instead of the first one as a basic. Not sure I understand the value in this (still heuristic) "uniquification".

Onboard with such a change?

**Comment by bensu** [comment]
In theory `doo.core/run-script` should support both absolute and relative paths. In practice this is a little more complicated, since the compiler and the environments have some quirks. The strategy so far was to take everything to absolute paths under `/tmp` and work from there. The value in unification was it was easier to reason about.

This week I'll refactor `doo.core` so that it works with boot-cljs-test.

**Comment by crisptrutski** [comment]
Makes sense, and looking forward to your solution. Just to note that the PR provided allows boot-cljs-test to work perfectly already, without breaking the lein plugin. But if there are deeper problems unresolved, have no objection waiting for your solution.

**Comment by bensu** [comment]
I just published your changes. My internal refactoring should keep no one waiting. I'll move this discussion to a new issue, about allowing for both absolute and relative paths consistently.

**Comment by crisptrutski** [comment]
Awesome! Thanks a lot :bow:
